### ISSUE TITLE
Homingz of Y and Z at the same time

### ISSUE THREAD

**Issue by Kedryn** [Little-Hobby-Shop/SunluS8#7]
Hi,
having X and Y homing at the same time has a problem.
When the hotend is low on the bed, and it's far from the X position, it will quickly go to it's Y home (a bit outside the bed) and hit both the clips holding the glass, removing them by force.
It's best to stick to X before Y.

**Comment by LittleHobbyShop** [comment]
Experience with this will vary based on where individuals put the bed clips. Marlin homes both X and Y together and depending which axis hits the stop first will affect which edge of the bed the head will run along. If it's causing you issues you have a some options:

1. Move your clips to a different position.
2. Replace the bulldog clips with Swiss clips. I highly recommend this, I use them and they have a much lower profile. A quick google for Swiss clips will show plenty of options, just make sure they're deep enough to accommodate the glass and aluminium bed.
3. Home your axis in whatever order you like by doing one at a time with parameters on [G28](https://marlinfw.org/docs/gcode/G028.html). This won't affect the **Auto Home** function on the LCD but in your start script in your slicer you could replace **G28** with:
**G28 X**
**G28 Y**
**G28 Z**
You can even lift your Z axis first if that helps and/or add the 0 parameter to prevent re-homing an already homed axis.

In an ideal world we would lift the Z axis before homing and I have this on other printers. Unfortunately, because of the way the S8 homes Z with an endstop on only one side, attempting to lift Z whilst the Z axis is right at the top of the printer could end up with one side crashing and throwing out the parallel with the bed with no automated way to recover it. So it has to be an individual choice rather than including it in firmware.
